# Generated by Django 4.2 on 2024-03-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cart_total_calories_cart_total_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Элементы корзины'},
        ),
    ]
