# Generated by Django 4.2 on 2024-03-01 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('scope', models.CharField(choices=[('sedentary', 'Малоподвижный образ жизни'), ('moderate', 'Умеренный уровень активности'), ('active', 'Активный образ жизни')], max_length=20)),
                ('activity_level', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField(null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'user_profile',
            },
        ),
    ]
