# Generated by Django 4.2 on 2024-03-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='scope',
            field=models.CharField(choices=[('weight_loss', 'Сброс веса'), ('maintenance', 'Поддержание формы'), ('muscle_gain', 'Набор мышечной массы')], max_length=20),
        ),
    ]
