# Generated by Django 4.2 on 2024-03-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Мужской'), (2, 'Женский')]),
        ),
    ]
