# Generated by Django 4.2 on 2024-03-03 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0004_alter_userprofile_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIMT',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('value', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('status_color', models.CharField(max_length=50)),
            ],
        ),
    ]
