# Generated by Django 4.2 on 2024-03-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userimt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimt',
            name='status_color',
        ),
    ]
