# Generated by Django 4.2 on 2024-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_userprofile_activity_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimt',
            options={'verbose_name': 'ИМТ', 'verbose_name_plural': 'ИМТ'},
        ),
        migrations.AddField(
            model_name='userimt',
            name='recommended_calories',
            field=models.IntegerField(default=0),
        ),
    ]
